Branch delete phone param
AY2324S2-CS2103T-T09-1/tp pull request #51
Opened 2024-03-15 08:39 UTC by yashma-sonara

2024-03-15 09:22 UTC, JiaXinEu requested changes
- Perhaps you might want to edit the files under `test/data/JSONAddressBookStorageTest` and `test/data/JSONSerializableAddressBookTest` to remove any phone parameter. 
- `JSONAdressBookStorageTest/invalidAndValidPersonAddressBook.json` is meant to consist of a valid and an invalid person, but in the master branch the data is invalid due to the phone number which has been removed in this PR. Maybe replacing it with another invalid parameter will help with passing the test.

2024-03-15 09:30 UTC, JiaXinEu approved these changes

2024-03-15 09:32 UTC, Wongqingyee commented on src/test/java/seedu/address/logic/commands/CommandTestUtil.java
> +    public static final String INVALID_PHONE_DESC = " " + "911a"; // 'a' not allowed in phones
Since we are removing the phone param, I think we dont need this line at all.

2024-03-15 09:32 UTC, Wongqingyee commented on src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
> +        String userInput = targetIndex.getOneBased() + INVALID_PHONE_DESC;
I think we dont need this line.
Can just declare the String userInput in line 164.

2024-03-15 09:39 UTC, Wongqingyee commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +        //phone = source.getPhone().value;
I think can just delete it instead of commenting it.

2024-03-15 09:43 UTC, Wongqingyee commented
I think can delete the Phone.java and PhoneTest.java too

2024-03-17 06:23 UTC, JiaXinEu commented
Seems like there are conflicts to be resolved before merging

2024-03-17 12:51 UTC, merged